### PR TITLE
Better -(NSString*)description for BFTask

### PR DESCRIPTION
**Pull request by JosephEarl**
See https://github.com/BoltsFramework/Bolts-iOS/pull/67 for the original PR.

Updated with @nlutsenko-fb comments and squashed. Also added a small test.

### CODE REVIEW

**Comment by JosephEarl** [comment]
Build needs re-running, tests passed but then

    /Users/travis/build.sh: line 41:  1181 Segmentation fault: 11  xcodebuild -project Bolts.xcodeproj -sdk macosx -scheme MacBolts

**Comment by nlutsenko-fb** [comment]
Re-enqueued build. 
![Xcode]
(http://cdn.meme.am/instances/500x/58496306.jpg)

**Comment by JosephEarl** [comment]
I just pushed a small changed that fixed the formatting (from `-(NSString*)description` to `- (NSString *)description`)

**Comment by nlutsenko-fb** [comment]
Looks great! Merging now.

**Pull request merged**
