### PR TITLE
Add backward compatible Obj-C Generic support for Tasks.

### PR DESCRIPTION
**Pull request by nlutsenko**
This support latest syntax in Xcode 7, and also is backward compatible via macro.
cc @grantland, @hallucinogen, @richardjrossiii

### CODE REVIEW

**Comment by grantland** [comment]
LGTM

**Comment by grantland** [comment]
Do we not have to update the implementation files?

**Comment by nlutsenko** [comment]
Aha, I am glad you asked - the answer is actually `no`, ObjC generics are only for interfaces/APIs and enforce replacement with `id` when used inside implementation (it resolves into a compiler error if used inside the implementation)

**Comment by grantland** [comment]
lol nice

**Comment by nlutsenko** [comment]
I've just updated the PR, so we have covariant support on this.
This is to enable something like this:
```objc
BFTask<NSString *> *stringTask = [BFTask taskWithResult:[NSString string]];
BFTask<NSMutableString *> *mutableStringTask = [BFTask taskWithResult:[NSMutableString string]];
stringTask = mutableStringTask; // This is valid, since NSMutableString is a subclass of NSString
```

**Comment by richardjrossiii** [comment]
<3 covariants.

**Comment by grantland** [comment]
even better!

**Pull request merged**
