### PR TITLE
Avoid unnecessary call to ‘continueWithBlock:’ when a task is completed

### PR DESCRIPTION
**Pull request by BrunoBerisso**
When a continuation block is executed with a BFExecutor the internal block that makes the actual call check if the continuation block returns a BFTask, if that is the case a call to ```continueWithBlock:``` is made and the completion source is updated accordingly to the result of the task.

This pull request add code to check if the returned task is complete and update the completion source without made an extra call to ```continueWithBlock:```. This increase the performance on memory consumption and execution time. And also make sence :)

### CODE REVIEW

**Comment by JosephEarl** [comment]
LGTM

**Comment by nlutsenko** [comment]
Took a while to get to, so sorry...
Will merge in tomorrow. Feel free to fix that one nit in the meantime.

**Comment by BrunoBerisso** [comment]
Hey, sorry for the delay on the ``completed`` / ``isCompleted`` detail. Should i open another pull request for this?

**Comment by nlutsenko** [comment]
`resultTask.completed` will go through using `isComplete` as it's a property access. `resultTask->_isCompleted` will use an ivar :D

You are more than welcome to open another pull request to use `resultTask.completed`. :+1:

**Comment by BrunoBerisso** [comment]
Got it, i don't use ``getter`` - ``setters`` to much :P
Thanks for the explanation, the new [pull request] is open.

Thanks for your awesome work with Bolts.

[pull request]: https://github.com/BoltsFramework/Bolts-iOS/pull/97

**Comment by BrunoBerisso** [comment]
Not sure what I suppose to do here.

**Comment by nlutsenko** [comment]
@BrunoBerisso, completely discard that message. Our GitHub bot went nuts a little bit yesterday.
We calmed him down and restrained him for now, so we don't get mass spam in future.

**Pull request merged**
