### PR TITLE
Better -(NSString*)description for BFTask

### PR DESCRIPTION
**Pull request by rogernolan**
As the title says. Nothing special here.

I didn't add test code as -description is only ever called during debug.

### CODE REVIEW

**Comment by JosephEarl** [comment]
@nlutsenko-fb what needs to be done to get this merged?

**Comment by nlutsenko-fb** [comment]
- Update the naming for `pragma mark` to `#pragma mark - NSObject`
- Kill change in Bolts.xccheckout
- Update description output to this pattern `<%@: %p; completed = %@; cancelled = %@;%@>` (last format argument is either ` result: %@;` or empty string)

**Comment by JosephEarl** [comment]
@nlutsenko-fb see https://github.com/BoltsFramework/Bolts-iOS/pull/78

**Comment by JosephEarl** [comment]
@nlutsenko-fb can close this since #78 is merged

**Comment by nlutsenko-fb** [comment]
Superseded by #78

**Pull request closed without merging**
